scalar Date

type User {
  id: ID!
  firstName: String!
  lastName: String!
  email: String!
  address: String!
  phone: String!
  password: String!
  products: [Product]
  purchases: [Purchase]
  rentals: [Rental]
  createdAt: Date!
  updatedAt: Date!
}

input ProductInput {
  title: String!
  categories: [ID!]!
  price: Float!
  rent: Float!
  rentInterval: String!
}
type Product {
  id: ID!
  title: String!
  description: String!
  price: Float
  rent: Float
  rentInterval: String
  categories: [Category]
  createdAt: Date!
  updatedAt: Date!
  ownerId: ID!
  owner: User!
  purchases: [Purchase]
  rentals: [Rental]
}

input ProductInput {
  title: String!
  description: String!
  categories: [ID!]
  price: Float!
  rent: Float!
  rentInterval: String!
  ownerId: String!
}

type Category {
  id: Int!
  name: String!
  Product: Product
  productId: ID
}

input CategoryInput {
  id: Int!
}

type Purchase {
  id: ID!
  userId: ID!
  user: User!
  productId: ID!
  product: Product!
  createdAt: Date!
}

type Rental {
  id: ID!
  userId: ID!
  user: User!
  productId: ID!
  product: Product!
  startDate: String!
  endDate: Date!
  createdAt: Date!
}

type Query {
  getUsers: [User]
  getProducts: [Product]
  getCategories: [Category]
  loginUser(email: String!, password: String!): User
}
type Mutation {
  createUser(
    firstName: String!
    lastName: String!
    email: String!
    address: String!
    phone: String!
    password: String!
  ): User
  createProduct(input: ProductInput!): Product!
  createCategory(name: String!, productId: ID): Category
}
